git:
  repo-path: '/Users/lshh/Desktop/IdeaProjects/_practice/msa-practice'
spring:
  profiles:
    name: local
  datasource:
    main:
      package: "lshh.codedelta"
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test
      maximum-pool-size: 20
      minimum-idle: 10
      username: sa
      password:
  jpa:
    hibernate:
#      ddl-auto: none
        ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        id.new_generator_mappings: true
server:
  port: 8080
  error:
    include-exception: true
    include-message: "always"
    include-stacktrace: "always"
    include-binding-errors: "always"
    whitelabel.enabled: false
logging:
  level:
    root: info
    web: debug
    core:
      handler:
        exception: debug
    com:
      microsoft.sqlserver: info
management:
  endpoint:
    health:
      show-details: always
      probes.enabled: true
      group:
        liveness.include: livenessState
        readiness.include: readinessState
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - liveness
          - readiness
          - env
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /index.html
  api-docs:
    path: /api-docs
  show-actuator: false
