server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: always
spring:
    datasource:
        default:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:test
#            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#            jdbc-url: jdbc:log4jdbc:h2:mem:test
            username: sa
            password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
                jdbc:
                    time_zone: UTC
            id.new_generator_mappings: true
security:
    authentication:
        secret-key: "authentication"
        expiration: 600000
    access:
        secret-key: "accessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccessaccess"
        expiration: 1800000
    refresh:
        secret-key: "refresh"
        expiration: 2592000000
logging:
    level:
        root: info
        sql: info
        web: debug
        org:
            hibernate:
                SQL: debug
                type: trace
            springframework:
                data.jpa.method.query: trace
                web.servlet.dispatcher: trace
management:
    endpoint:
        health:
            show-details: always
            enabled: true
            probes:
                enabled: true
        info:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - health
                    - info
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: /index.html
    api-docs:
        path: /v3/api-docs
    show-actuator: false