
CREATE TABLE [dbo].[COMMIT_HIST](
    [COMMIT_ID] [bigint] IDENTITY(1,1) NOT NULL,
    [COMMIT_POIN] [varchar](100) NOT NULL,
    [COMP_COMMIT_POIN] [varchar](100) NULL,
    [COMMIT_REGP_ID] [varchar](100) NULL,
    [COMMIT_REG_DTM] [datetime2](7) NULL,
    [COMMIT_COMT] [varchar](3000) NULL,
    [APPR_YN] [char](1) NOT NULL,
    [REGP_ID] [varchar](100) NULL,
    [REG_DTM] [datetime2](1) NULL,
    [UPDP_ID] [varchar](100) NULL,
    [UPD_DTM] [datetime2](1) NULL,
    [GLOB_UID] [varchar](40) NULL,
    CONSTRAINT [PK_CM_HIST] PRIMARY KEY CLUSTERED
(
[COMMIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]


CREATE TABLE [dbo].[QUERY_DIFF](
    [DIFF_ID] [bigint] IDENTITY(1,1) NOT NULL,
    [QUERY_PATH] [varchar](200) NULL,
    [COMMIT_ID] [bigint] NOT NULL,
    [RECEN_ID] [bigint] NULL,
    [COMMIT_CONT] [text] NULL,
    [RECEN_CONT] [text] NULL,
    [APPR_YN] [char](1) NULL,
    [CHAN_TYPE] [varchar](10) NULL,
    [REGP_ID] [varchar](100) NULL,
    [REG_DTM] [datetime2](1) NULL,
    [UPDP_ID] [varchar](100) NULL,
    [UPD_DTM] [datetime2](1) NULL,
    [GLOB_UID] [varchar](40) NULL,
    CONSTRAINT [ID] PRIMARY KEY CLUSTERED
(
[DIFF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]